// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Erabikata.Models.Input;
//
//    var sentence = Sentence.FromJson(jsonString);

using Newtonsoft.Json;

namespace Erabikata.Models.Input
{
    public partial class Sentence
    {
        [JsonProperty("analyzed")] public Analyzed[] Analyzed { get; set; }

        [JsonProperty("startTime")] public double StartTime { get; set; }

        [JsonProperty("tokenized")] public string[] Tokenized { get; set; }
    }

    public partial class Sentence
    {
        public static Sentence[] FromJson(string json)
        {
            return JsonConvert.DeserializeObject<Sentence[]>(json, Converter.Settings);
        }
    }
}